/**
 * All API shapes come from the contracts package (source of truth, pinned by
 * the platform's contract-first rule). This module is the only place that
 * touches the generated file; feature code imports from here.
 */
import type { components } from '@deidos-eats/contracts/generated/typescript'

type Schemas = components['schemas']

export type Restaurant = Schemas['Restaurant']
export type RestaurantList = Schemas['RestaurantList']
export type BranchSummary = Schemas['BranchSummary']
export type Branch = Schemas['Branch']
export type OpeningHour = Schemas['OpeningHours']
export type Menu = Schemas['Menu']
export type MenuCategory = Schemas['MenuCategory']
export type MenuItem = Schemas['MenuItem']
export type ModifierGroup = Schemas['ModifierGroup']
export type ModifierOption = Schemas['ModifierOption']
export type Allergen = Schemas['Allergen']

export type CartLineInput = Schemas['CartLineInput']
export type CartValidateRequest = Schemas['CartValidateRequest']
export type PricedCart = Schemas['PricedCart']
export type PricedCartLine = Schemas['PricedCartLine']

export type CheckoutRequest = Schemas['CheckoutRequest']
export type CheckoutResponse = Schemas['CheckoutResponse']

export type Order = Schemas['Order']
export type OrderSummary = Schemas['OrderSummary']
export type OrderList = Schemas['OrderList']
export type OrderStatus = Schemas['OrderStatus']
export type PaymentStatus = Schemas['PaymentStatus']
export type FulfillmentType = Schemas['FulfillmentType']

export type User = Schemas['User']
export type StaffBranchMembership = Schemas['StaffBranchMembership']
export type StaffBranchMembershipList = Schemas['StaffBranchMembershipList']
export type UserUpdate = Schemas['UserUpdate']
export type Address = Schemas['Address']
export type AddressCreate = Schemas['AddressCreate']
export type AddressList = Schemas['AddressList']
export type DeviceRegistration = Schemas['DeviceRegistration']
export type Device = Schemas['Device']

export type MarketplaceHome = Schemas['MarketplaceHome']
export type MarketplaceBanner = Schemas['MarketplaceBanner']
export type MarketplaceItem = Schemas['MarketplaceItem']
export type MarketplaceBranch = Schemas['MarketplaceBranch']
export type MarketplaceContent = Schemas['MarketplaceContent']

export type MenuCatalogItem = Schemas['MenuCatalogItem']
export type MenuCatalogPage = Schemas['MenuCatalogPage']
export type MenuItemUpdate = Schemas['MenuItemUpdate']
export type PromoState = Schemas['PromoState']
export type AdminBranch = Schemas['AdminBranch']
export type AdminBranchList = Schemas['AdminBranchList']
export type AdminRestaurant = Schemas['AdminRestaurant']
export type AdminRestaurantList = Schemas['AdminRestaurantList']
export type AdminBanner = Schemas['AdminBanner']
export type AdminBannerList = Schemas['AdminBannerList']
export type AdminBannerCreate = Schemas['AdminBannerCreate']
export type AdminBannerUpdate = Schemas['AdminBannerUpdate']
export type OvenFeature = Schemas['OvenFeature']
export type OvenFeatureList = Schemas['OvenFeatureList']
export type OvenFeatureCreate = Schemas['OvenFeatureCreate']
export type OvenFeatureUpdate = Schemas['OvenFeatureUpdate']
export type SiteContentKey = Schemas['SiteContentKey']
export type SiteContentEntry = Schemas['SiteContentEntry']
export type SiteContentList = Schemas['SiteContentList']
export type SiteContentUpdate = Schemas['SiteContentUpdate']
export type AdminRestaurantCreate = Schemas['AdminRestaurantCreate']
export type AdminRestaurantUpdate = Schemas['AdminRestaurantUpdate']
export type AdminBranchCreate = Schemas['AdminBranchCreate']
export type AdminBranchUpdate = Schemas['AdminBranchUpdate']
export type AdminStaffMember = Schemas['AdminStaffMember']
export type AdminStaffMembership = Schemas['AdminStaffMembership']
export type AdminStaffMembershipInput = Schemas['AdminStaffMembershipInput']
export type AdminStaffList = Schemas['AdminStaffList']
export type AdminStaffCreate = Schemas['AdminStaffCreate']
export type AdminStaffCreateResult = Schemas['AdminStaffCreateResult']
export type AdminStaffMemberUpdate = Schemas['AdminStaffMemberUpdate']
export type AdminStaffPasswordReset = Schemas['AdminStaffPasswordReset']
export type StaffBranchRole = Schemas['StaffBranchRole']
export type ImageUploadRequest = Schemas['ImageUploadRequest']
export type ImageUploadResponse = Schemas['ImageUploadResponse']

export type ApiErrorBody = Schemas['Error']
export type OrderChangedMessage = Schemas['OrderChangedMessage']
